[package]
name = "aoc1"
version = "0.1.0"
authors = ["Mydayyy <mydayyy@mydayyy.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "aoc1"
path = "main.rs"
